# Server

server.port=${PORT:8080}
server.tomcat.max-connections=10000
server.tomcat.accept-count=100
server.tomcat.max-threads=500

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/qr_restaurant_saas
spring.datasource.username=postgres
spring.datasource.password=Ashokreddy@67
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000
spring.data.redis.lettuce.pool.max-active=20
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=2

# JWT
jwt.secret=mySuperSecretKeyThatIsAtLeast32CharactersLongForHS256
jwt.expiration=3600000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kunduruashokreddy7@gmail.com
spring.mail.password=oackwfiobrddmfix
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend URL (used in email links)
app.frontend-url=http://localhost:3000
spring.datasource.hikari.maximum-pool-size=50
# Logging
# Disable rate limiting for load tests
rate-limiter.enabled=false
logging.level.com.qrplatform.backend=DEBUG
logging.level.org.springframework.security=INFO