# ======================
# SERVER
# ======================
server.port=8080

# ======================
# DATABASE (LOCAL POSTGRES)
# ======================
spring.datasource.url=jdbc:postgresql://localhost:5432/qr_restaurant_saas
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ======================
# JWT
# ======================
jwt.secret=9b8c4a6d2e7f1c3a5d8e6b4c2f9a1d7e3b6c8f2a4d9e1c7b5a3f6e8d2c4b1a9f
jwt.expiration=3600000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kunduruashokreddy7@gmail.com
spring.mail.password=bcajmktirngkilom
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true